tests:
  services:
    - postgres:9.5
  script:
    - angr-test sync hard
    - pip install -e .
    - ~/angr/farnsworth/setupdb.sh ~/angr/farnsworth/.env.test
    - nosetests tests/
  tags: ["angr"]

# lint:
#   script: "lint.py"
#   tags: ["cgc-linter"]

docs:
  script: "generate_docs"
  tags: ["cgc-linter"]
