stages:
  - test
  - build
  - deploy

# tests:
#   services:
#     - postgres:9.5
#   script:
#     - angr-test sync hard
#     - pip install -e .
#     - ~/angr/farnsworth/setupdb.sh ~/angr/farnsworth/.env.test
#     - nosetests tests/
#   tags: ["angr"]

# lint:
#   script: "lint.py"
#   tags: ["cgc-linter"]

docs:
  stage: build
  script: "generate_docs"
  tags: ["cgc-linter"]

build_images:
  stage: deploy
  only: ["master"]
  script:
  - cgc-build worker
  tags: ["docker-builder"]

production:
  stage: deploy
  only: ["master"]
  script:
  - docker tag worker 172.16.7.72/worker:stable
  - docker push 172.16.7.72/worker:stable
  environment: production
  tags: ["docker-builder"]
